// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import EditCommentController from "./edit_comment_controller"
application.register("edit-comment", EditCommentController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import HideAlertController from "./hide_alert_controller"
application.register("hide-alert", HideAlertController)

import TurboModalController from "./turbo_modal_controller"
application.register("turbo-modal", TurboModalController)
